# Generated by Django 4.1.4 on 2023-10-05 07:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mill', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mill',
            name='bazar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bazar_person', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mill',
            name='mill',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4')], default=2),
        ),
        migrations.AlterUniqueTogether(
            name='mill',
            unique_together={('date', 'member')},
        ),
    ]
