# Generated by Django 4.2.4 on 2023-10-08 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amount', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diposit',
            name='ststus',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Exp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('diposit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amount.diposit')),
            ],
        ),
    ]
