# Generated by Django 4.2.4 on 2023-10-08 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amount', '0002_diposit_ststus_exp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exp',
            name='amount',
        ),
        migrations.AddField(
            model_name='exp',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
