# Generated by Django 4.1.4 on 2023-10-09 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amount', '0004_commonexp'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonexp',
            name='billed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='commonexp',
            name='cook',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commonexp',
            name='month',
            field=models.CharField(choices=[('1', 'January'), ('2', 'February'), ('3', 'March'), ('4', 'April'), ('5', 'May'), ('6', 'June'), ('7', 'July'), ('8', 'August'), ('9', 'September'), ('10', 'October'), ('11', 'November'), ('12', 'December')], default='1', max_length=2),
        ),
        migrations.AddField(
            model_name='commonexp',
            name='year',
            field=models.IntegerField(default=2023, editable=False),
        ),
        migrations.AlterField(
            model_name='commonexp',
            name='electric',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commonexp',
            name='rice',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='commonexp',
            unique_together={('month', 'year')},
        ),
        migrations.RemoveField(
            model_name='commonexp',
            name='coock',
        ),
        migrations.RemoveField(
            model_name='commonexp',
            name='date',
        ),
    ]
