# Generated by Django 4.1.4 on 2023-10-09 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amount', '0005_commonexp_billed_commonexp_cook_commonexp_month_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonexp',
            name='month',
            field=models.IntegerField(choices=[('1', 'January'), ('2', 'February'), ('3', 'March'), ('4', 'April'), ('5', 'May'), ('6', 'June'), ('7', 'July'), ('8', 'August'), ('9', 'September'), ('10', 'October'), ('11', 'November'), ('12', 'December')], default='1'),
        ),
    ]
