# Generated by Django 4.1.4 on 2023-10-09 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amount', '0006_alter_commonexp_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonexp',
            name='year',
            field=models.IntegerField(default=2023),
        ),
    ]
