# Generated by Django 4.1.4 on 2023-10-09 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amount', '0009_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='diposit',
            field=models.IntegerField(default=0),
        ),
    ]
